#!/bin/sh
PATH="/usr/local/bin:$PATH"

#
# Run WordPress coding standards tasks.
#
# vendor/bin/phpcs --config-set installed_paths vendor/wp-coding-standards/wpcs
wplint=`vendor/bin/phpcs --standard=WordPress --ignore=*/vendor/*,*/node_modules/* --filter="gitstaged" .`
echo "$wplint";

if [[ "$wplint" == *"FOUND"* ]]
	then
		hasLintErrors="true"
fi

#
# Run Sass lint task.
#
SASSFILES=`git diff --cached --name-only --diff-filter=AM | grep '.scss$'`
if [[ -z $SASSFILES ]]
then
	echo ""
else
	for file in ${SASSFILES}
	do
		cssFilesStr="$cssFilesStr$cssFilesSeparator$file"
		cssFilesSeparator=", "
	done

	lint=`node_modules/.bin/sass-lint "$cssFilesStr" -v -q`
	echo "$lint"

	if [[ "$lint" == *"problem"* ]]
		then
			hasLintErrors="true"
	fi
fi

#
# Report errors
#
if [ $hasLintErrors ]; then
	echo "Fix all issues before commit."
	exit 1
fi

exit 0
